In [11]:
import pandas as pd
import numpy as np
import random
import sklearn.manifold as manifold
import colorsys

import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

In [12]:
# Read acceleration data
acceleration_data = pd.read_csv("../output/handshape_acceleration.csv")

acceleration_data.head()

   frame      time  acceleration
0      0  0.000000      0.032021
1      1  0.016667      0.028401
2      2  0.033333      0.020629
3      3  0.050000      0.007888
4      4  0.066667     -0.006882

In [13]:
# Read segment data
segment_data = pd.read_csv("../output/handshape_segments.csv")

segment_data.head()

   start  end                                       average_pose
0      0  129  RightHandMiddle1:0.972685 0.0350125 0.229324 -...
1    136  158  RightHandMiddle1:0.916301 0.041745 0.397896 -0...
2    164  168  RightHandMiddle1:0.976501 0.0308876 0.213186 -...
3    175  179  RightHandMiddle1:0.939865 0.00371143 0.341523 ...
4    184  191  RightHandMiddle1:0.970215 0.027404 0.240595 -0...

In [14]:
# # Add hand_index data to acceleration_data (so add an index based on the hand and its)
# acceleration_data['hand_index'] = acceleration_data.groupby('hand').cumcount()

# acceleration_data.head()

In [15]:
fig = go.Figure()

fig.add_trace(
    go.Scatter(
        x=acceleration_data["frame"],
        y=acceleration_data["acceleration"],
        mode="lines",
        line=dict(color="#1f77b4", width=1.5),
        name="Base",
        legendgroup="Base",
    )
)

colours = px.colors.qualitative.Plotly

for index, row in segment_data.iterrows():
    current_color = colours[index % len(colours)]

    segment_slice = acceleration_data[
        (acceleration_data["frame"] >= row["start"])
        & (acceleration_data["frame"] <= row["end"])
    ]

    if not segment_slice.empty:
        fig.add_trace(
            go.Scatter(
                x=segment_slice["frame"],
                y=segment_slice["acceleration"],
                mode="lines",
                line=dict(color=current_color, width=4),
                name=f"Seg {index}",
                legendgroup=f"Segment {index}",
                showlegend=True,
            )
        )

fig.update_layout(
    title_text="Hand Acceleration Data",
    height=600,
    showlegend=True,
    xaxis_title="Time (s)",
    yaxis_title="Acceleration (rad/s²)",
)

fig.show()